# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  hadolint_executor:
    parameters:
        tag:
          type: string
          default: "v1.6.6-6-g254b4ff"
    docker:
       - image: hadolint/hadolint:<<parameters.tag>>
  
  python_executor:
    parameters:
       tag:
         type: string
         default: "3.6.1"
    docker:
      - image: circleci/python:<<parameters.tag>>
    working_directory: ~/repo

jobs:
  python_executor:
      executor: python_executor
      steps:
        - run_pythonlint
  docker_lint: 
      executor: hadolint_executor
      steps:
       - run_dockerfile_lint
          
commands:
  run_dockerfile_lint:
    steps:
      - checkout
      - run:
         name: Dockerfile Lint
         command: |
           hadolint Dockerfile
           
  run_pythonlint:
     steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
    
workflows:
  version: 2
   jobs:
    - python_executor
    - docker_lint

